name: CD - Con Aprobación en producción
on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch: null
jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy a DEV
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_DEV }}
  deploy-qa:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy a QA
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_QA }}
  deploy-prd:
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy a PRD
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_PRD }}