name: Python CI/CD

on:
  push:
    branches: [ feature/* ] #solo se ejecuta cuando el push es en una rama que empieza con feature/
  pull_request:
    # branches: [ develop, main ] #solo se ejecuta cuando se hace un pull request a qa o main
    branches: [ develop, main ] #solo se ejecuta cuando se hace un pull request a homologacion o main    

jobs:

  test:
    runs-on: ubuntu-latest # worker o runner donde se ejecuta el job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # baja el codigo

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # setea la version de python a usar en el job

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt #instala dependencias.. no hace falta tener dos requirements pero es una buena practica separar las de produccion de las de desarrollo

      - name: Lint code
        run: |
          flake8 app

      - name: Security scan (bandit)
        run: |
          bandit -r app ## https://github.com/PyCQA/bandit

      - name: Dependency vulnerability scan
        run: |
          pip-audit

      - name: Run unit tests
        run: |
          pytest tests/unit

      - name: Run integration tests
        run: |
          pytest tests/integration

      - name: Coverage report
        run: |
          pytest --cov=app --cov-report=xml --cov-report=term #esto lo pueden cambiar por sonar pero q sea el gratis

  deploy:

    needs: test

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' #solo se ejecuta cuando el push es en main

    steps:

      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
